name: Workflow

on:
  push:
    branches:
      - main

env:
  DIR1: false
  DIR2: false
  DIR3: false
  DIR4: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for changed directory in the last commit
        id: check
        run: |
          echo $(git log --stat -1 --oneline) > log.txt
          if grep -q "Dir1" log.txt; then
            { echo "DIR1=true" ; } >> $GITHUB_ENV
          if grep -q "Dir2" log.txt; then
            { echo "DIR2=true" ; } >> $GITHUB_ENV
          if grep -q "Dir3" log.txt; then
            { echo "DIR3=true" ; } >> $GITHUB_ENV
          if grep -q "Dir4" log.txt; then
            { echo "DIR4=true" ; } >> $GITHUB_ENV
          fi
      - name: Echo all the enviroment variables to test
        run: |
          echo $DIR1
          echo $DIR2
          echo $DIR3
          echo $DIR4
